#**Thông tin sinh viên:**

* MSSV: 19521388
* Họ và tên: Hoàng Tiến Dũng
* Lớp môn học: CS331.M11
* Bài tập: Cài đặt thuật toán Gradient Descent bằng Numpy và Tensorflow

#**Bài làm:**

In [4]:
import numpy as np
import tensorflow as tf
import pandas as pd

#**cost = 1/2m * sum((X*theta - y)^2**

#**I. Implement Gradient Descent theo Numpy**

In [104]:
def cost_func(X, y, theta):
  # y là 1 vector cột
  m = len(y)
  y_pred = X@theta
  return (1/(2*m)) * np.sum((y_pred-y)**2)

In [105]:
def gradient_descent(X, y, theta, alpha, iters):
  m = len(y)
  costs = []
  for i in range(iters):
    y_pred = X@theta
    theta -= (alpha/m * (X.T@(y_pred-y))) #Vector hóa
    costs.append(cost_func(X, y,theta))
  return theta, costs

#**II. Implement Gradient Descent theo Tensorflow**

In [106]:
def cost_func_tf(X, y, theta):
  # y là 1 vector cột
  y_pred = tf.matmul(X, theta)
  return 1/2 * tf.reduce_mean(tf.square(y_pred-y))

In [123]:
def gradient_descent_tf(X, y, theta, alpha, iters):
  costs = []
  for iter in range(iters):
    with tf.GradientTape() as t:
      t.watch(theta)
      cost_f = cost_func_tf(X, y, theta)
      dtheta = t.gradient(cost_f,theta)
      theta -= alpha*dtheta

      costs.append(cost_f)
  costs.append(cost_func_tf(X, y, theta))
  return theta, costs

#**III.Thử nghiệm**

##**1. Dữ liệu**

In [108]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [109]:
df = pd.read_csv('/content/drive/MyDrive/Private_ThiGiacMayTinhNangCao/Real estate.csv', index_col=0)
df_new = df.drop(df.columns[[0,2]], axis=1)
X = df_new.iloc[:,0:4]
y = df_new.iloc[:,-1]

In [110]:
X=X.to_numpy()
y=y.to_numpy()
print(X)
print(y)

[[ 32.       10.       24.98298 121.54024]
 [ 19.5       9.       24.98034 121.53951]
 [ 13.3       5.       24.98746 121.54391]
 ...
 [ 18.8       7.       24.97923 121.53986]
 [  8.1       5.       24.96674 121.54067]
 [  6.5       9.       24.97433 121.5431 ]]
[ 37.9  42.2  47.3  54.8  43.1  32.1  40.3  46.7  18.8  22.1  41.4  58.1
  39.3  23.8  34.3  50.5  70.1  37.4  42.3  47.7  29.3  51.6  24.6  47.9
  38.8  27.   56.2  33.6  47.   57.1  22.1  25.   34.2  49.3  55.1  27.3
  22.9  25.3  47.7  46.2  15.9  18.2  34.7  34.1  53.9  38.3  42.   61.5
  13.4  13.2  44.2  20.7  27.   38.9  51.7  13.7  41.9  53.5  22.6  42.4
  21.3  63.2  27.7  55.   25.3  44.3  50.7  56.8  36.2  42.   59.   40.8
  36.3  20.   54.4  29.5  36.8  25.6  29.8  26.5  40.3  36.8  48.1  17.7
  43.7  50.8  27.   18.3  48.   25.3  45.4  43.2  21.8  16.1  41.   51.8
  59.5  34.6  51.   62.2  38.2  32.9  54.4  45.7  30.5  71.   47.1  26.6
  34.1  28.4  51.6  39.4  23.1   7.6  53.3  46.4  12.2  13.   30.6  59.6
  31.3

##**2. Khởi tạo**

In [111]:
theta = np.zeros((5,1)) #4 đặc trưng, 5 giá trị
X = np.append(np.ones((len(y),1)), X, axis=1)

In [112]:
X

array([[  1.     ,  32.     ,  10.     ,  24.98298, 121.54024],
       [  1.     ,  19.5    ,   9.     ,  24.98034, 121.53951],
       [  1.     ,  13.3    ,   5.     ,  24.98746, 121.54391],
       ...,
       [  1.     ,  18.8    ,   7.     ,  24.97923, 121.53986],
       [  1.     ,   8.1    ,   5.     ,  24.96674, 121.54067],
       [  1.     ,   6.5    ,   9.     ,  24.97433, 121.5431 ]])

In [113]:
y = y.reshape((414,1))
y.shape

(414, 1)

##**3. Gradient Descent với Numpy**

In [114]:
theta = np.zeros((5,1))

In [115]:
theta, costs = gradient_descent(X, y, theta, 0.1, 5)

In [116]:
print(theta)

[[2.31444177e+13]
 [4.13358520e+14]
 [9.48579937e+13]
 [5.77893982e+14]
 [2.81281882e+15]]


In [117]:
print(costs)

[1778751137.3586333, 4394465303534660.0, 1.0856681285285312e+22, 2.682181343842815e+28, 6.626423464239508e+34]


##**4. Gradient Descent với Tensorflow**

In [124]:
theta = np.zeros((5,1))

In [125]:
X_tf = tf.convert_to_tensor(X)
y_tf = tf.convert_to_tensor(y)
theta_tf = tf.convert_to_tensor(theta)
theta, costs = gradient_descent_tf(X_tf, y_tf, theta_tf, 0.1, 5)

In [126]:
print(theta)

tf.Tensor(
[[2.31444177e+13]
 [4.13358520e+14]
 [9.48579937e+13]
 [5.77893982e+14]
 [2.81281882e+15]], shape=(5, 1), dtype=float64)


In [127]:
print(costs)

[<tf.Tensor: shape=(), dtype=float64, numpy=813.5921980676328>, <tf.Tensor: shape=(), dtype=float64, numpy=1778751137.3586342>, <tf.Tensor: shape=(), dtype=float64, numpy=4394465303534663.5>, <tf.Tensor: shape=(), dtype=float64, numpy=1.085668128528533e+22>, <tf.Tensor: shape=(), dtype=float64, numpy=2.682181343842819e+28>, <tf.Tensor: shape=(), dtype=float64, numpy=6.626423464239521e+34>]
