<a href="https://colab.research.google.com/github/htdung167/learn-machine-learning/blob/main/4.%20Tensorflow/tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
# Check GPU
print(tf.config.list_physical_devices('GPU'))

[]


In [3]:
# Check CPU
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

##**Init**

In [4]:
import tensorflow as tf
import numpy as np

In [5]:
# create a ndarray
a_list = [1, 2, 3, 4]
data_np = np.array(a_list)
print(type(data_np))
print(data_np)

<class 'numpy.ndarray'>
[1 2 3 4]


In [6]:
# convert from ndarray to tensor
data_tf = tf.convert_to_tensor(data_np)
print(data_tf)
print(data_tf.shape)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)
(4,)


In [7]:
# reshape in tf
data_tf_2 = tf.reshape(data_tf, (2,2))
print(data_tf_2)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


In [8]:
# convert from tensor to ndarray
data_np_2 = data_tf_2.numpy()
print(data_np_2)

[[1 2]
 [3 4]]


#**Broadcasting**

In [9]:
tensor_1 = tf.convert_to_tensor([[1, 2], [3, 4]])
tensor_2 = tf.convert_to_tensor([1,2])

# add two tensor
tensor_3 = tensor_1 + tensor_2

print('tensor_1: \n', tensor_1)
print('tensor_2: \n', tensor_2)
print('tensor_3: \n', tensor_3)

tensor_1: 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tensor_2: 
 tf.Tensor([1 2], shape=(2,), dtype=int32)
tensor_3: 
 tf.Tensor(
[[2 4]
 [4 6]], shape=(2, 2), dtype=int32)


In [10]:
tensor_4 = tf.convert_to_tensor([[1, 2], [3, 4]])

# add a number to a tensor
tensor_5 = tensor_4 + 2

print('tensor_4: \n', tensor_4)
print('tensor_5: \n', tensor_5)

tensor_4: 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tensor_5: 
 tf.Tensor(
[[3 4]
 [5 6]], shape=(2, 2), dtype=int32)


#**Math**

##**Squared Difference**

In [11]:
# create a list
x = [1,2,3,4]
y = 5
sd = tf.math.squared_difference(x, y)
print(sd)

tf.Tensor([16  9  4  1], shape=(4,), dtype=int32)


In [12]:
# create a tensor
x = tf.convert_to_tensor([1,2,3,4])
y = 5

sd = tf.math.squared_difference(x, y)
print(sd)

tf.Tensor([16  9  4  1], shape=(4,), dtype=int32)


In [13]:
# create an ndarray
x = np.array([1,2,3,4])
y = 5
sd = tf.math.squared_difference(x, y)
print(sd)

tf.Tensor([16  9  4  1], shape=(4,), dtype=int64)


#**Important functions**

In [14]:
rand = tf.random.normal(shape=(3,2), mean=0, stddev=1)
print(rand)

tf.Tensor(
[[-0.8539857  -1.0091962 ]
 [-0.05310676 -1.7839335 ]
 [ 0.975181    0.07900026]], shape=(3, 2), dtype=float32)


In [16]:
rand = tf.random.uniform(shape=(3,2), minval=0, maxval=9, dtype=tf.int32)
print(rand)

tf.Tensor(
[[8 1]
 [3 2]
 [1 8]], shape=(3, 2), dtype=int32)


In [18]:
# concatenate
tensor_1 = tf.random.uniform(shape=(2,2), minval=0, maxval=9, dtype=tf.int32)
tensor_2 = tf.random.uniform(shape=(2,2), minval=0, maxval=9, dtype=tf.int32)

tensor_3 = tf.concat([tensor_1, tensor_2], axis=0)
tensor_4 = tf.concat([tensor_1, tensor_2], axis=1)

print('tensor_1: \n', tensor_1)
print('tensor_2: \n', tensor_2)
print('tensor_3: \n', tensor_3)
print('tensor_4: \n', tensor_4)



tensor_1: 
 tf.Tensor(
[[1 5]
 [7 4]], shape=(2, 2), dtype=int32)
tensor_2: 
 tf.Tensor(
[[2 3]
 [4 6]], shape=(2, 2), dtype=int32)
tensor_3: 
 tf.Tensor(
[[1 5]
 [7 4]
 [2 3]
 [4 6]], shape=(4, 2), dtype=int32)
tensor_4: 
 tf.Tensor(
[[1 5 2 3]
 [7 4 4 6]], shape=(2, 4), dtype=int32)


In [20]:
# argmax
tensor = tf.random.uniform(shape=(3,6), minval=0, maxval=9, dtype=tf.int32)
max_pos_1 = tf.argmax(tensor, axis=0)
max_pos_2 = tf.argmax(tensor, axis=1)
print(tensor)
print(max_pos_1)
print(max_pos_2)

tf.Tensor(
[[5 4 0 6 3 6]
 [5 2 7 6 5 7]
 [0 1 5 6 4 7]], shape=(3, 6), dtype=int32)
tf.Tensor([0 0 1 0 1 1], shape=(6,), dtype=int64)
tf.Tensor([3 2 5], shape=(3,), dtype=int64)


In [26]:
# matmul : Tich vo huong
matrix = tf.convert_to_tensor([[1,2],[3,4]])
vector = tf.convert_to_tensor([1,2])

vector = tf.reshape(vector, shape=(2,1))

print(matrix)
print(vector)
print("Cach 1: ", tf.matmul(matrix, vector))
print("Cach 2: ", matrix@vector)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)
Cach 1:  tf.Tensor(
[[ 5]
 [11]], shape=(2, 1), dtype=int32)
Cach 2:  tf.Tensor(
[[ 5]
 [11]], shape=(2, 1), dtype=int32)


In [31]:
# Variable: Khi tính toán không tạo vùng nhớ mới
var = tf.Variable([1.0, 2.0])
print(var.numpy())

var.assign([7,9])
print(var.numpy())

var.assign_add([5,3]) # + [5,3]
print(var.numpy())

var.assign_sub([2,3]) # - [2,3]
print(var.numpy())

[1. 2.]
[7. 9.]
[12. 12.]
[10.  9.]


In [33]:
# Reduce sum : Cộng tổng lại và giảm chiều
x = tf.convert_to_tensor([1,2,3,4])
sum_value = tf.reduce_sum(x)
print(sum_value)

tf.Tensor(10, shape=(), dtype=int32)


#**Gradient computation**

In [2]:
import tensorflow as tf

x = tf.ones((2,2))

with tf.GradientTape() as t:
  t.watch(x)
  y = tf.reduce_sum(x) # y = x1 + x2 + x3 + x4
  z = tf.multiply(y,y) # z = y^2

dz_dx = t.gradient(z, x)

print(x)
print(dz_dx)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


In [4]:
x = tf.constant(3.0)

with tf.GradientTape(persistent=True) as t: 
  # khi tính đạo hàm nhiều lần nên có persistent = True 
  t.watch(x)
  y = x*x # y = x*x
  z = y*y # z = y*y

# compute derivative
dz_dx = t.gradient(z, x)
dy_dx = t.gradient(y, x)

print(dz_dx)
print(dy_dx)

tf.Tensor(108.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


In [23]:
x = tf.Variable(1.0) # có variable nên gradient tự tìm

with tf.GradientTape() as t1:
  # t1.watch(x)
  with tf.GradientTape() as t2:
    # t2.watch(x)
    y = x*x*x  # y = x^3
  dy_dx = t2.gradient(y,x)  # y'

d2y_d2x = t1.gradient(dy_dx, x) #y''

print(dy_dx)
print(d2y_d2x)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


In [11]:
x = tf.ones((1)) * 2

with tf.GradientTape() as t:
  t.watch(x)
  g = -3 * x + 4 # g = -3*x+4
  h = 2 * g + 1 # h = 2*g+1

dh_dx = t.gradient(h, x)

print(dh_dx)

tf.Tensor([-6.], shape=(1,), dtype=float32)


In [15]:
x = tf.ones((1))

with tf.GradientTape() as t:
  t.watch(x)
  g = x*x + 1 # g = x^2 + 1
  h = tf.exp(g) # h = e^g

dh_dx = t.gradient(h, x)

print(dh_dx)

tf.Tensor([14.778112], shape=(1,), dtype=float32)


In [21]:
x = tf.ones((1))

with tf.GradientTape() as t:
  t.watch(x)
  g = tf.cos(x*x*tf.exp(x) + 2*x)  # g = cos(x^2 * e^x + 2x)
  h = tf.exp(g) * tf.sin(tf.sqrt(g)) # h = e^g * sin(sqrt(g))

dh_dx = t.gradient(h, x)

print(dh_dx)

tf.Tensor([67.120346], shape=(1,), dtype=float32)
